### ISSUE TITLE
Iterate could return invisibly

### ISSUE THREAD

**Issue by dfalbel** [lionel-/flowery#10]
Iterate will always return a `NULL` when finishing the iteration. Can we make this invisible?

``` r
library(flowery)

iterate(
  for (x in as_iterator(1:3)) {
    print(x)
  }
)
#> [1] 1
#> [1] 2
#> [1] 3
#> NULL
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
That makes sense, this would be consistent with `for`.

**Comment by dfalbel** [comment]
Ok! I can make a PR for this later today
